system:
    farte:
        block_view:
            reiseplanlegger:
                template: tfkfarteBundle:block:reiseplanlegger.html.twig
                match:
                    Type: Reiseplanlegger

ezpage:
    layouts:
        Forside:
            name: Forside layout
            template: "tfkfarteBundle:zone:forsidelayout.html.twig"

    enabledLayouts:
        - Forside
