system:
    farte:
        block_view:
            slider:
                template: tfkfarteBundle:block:slider.html.twig
                match:
                    Type: Slider
            reiseplanlegger:
                template: tfkfarteBundle:block:slider.html.twig
                match:
                    Type: Reiseplanlegger
            kampanje:
                template: tfkfarteBundle:block:kampanje.html.twig
                match:
                    Type: Kampanje
            listebokser:
                template: tfkfarteBundle:block:listebokser.html.twig
                match:
                    Type: Listebokser
            fargebokser:
                template: tfkfarteBundle:block:fargebokser.html.twig
                match:
                    Type: Fargebokser
        location_view:
            listebokser_item:
                folder:
                    controller: tfkfarteBundle:Item:listeblokkInitFolder
                    template: tfkfarteBundle:block:block_items/listebokser_folder.html.twig
                    match:
                        Identifier\ContentType: "folder"
                infobox:
                    template: tfkfarteBundle:block:block_items/listebokser_infobox.html.twig
                    match:
                        Identifier\ContentType: "infobox"
            fargebokser_item:
                folder:
                    template: tfkfarteBundle:block:block_items/fargebokser_folder.html.twig
                    match:
                        Identifier\ContentType: "folder"
        content_view:
            listebokser_item_list:
                article:
                    template: tfkfarteBundle:block:block_items/listebokser_article.html.twig
                    match:
                        Identifier\ContentType: "article"
                folder:
                    template: tfkfarteBundle:block:block_items/listebokser_subfolder.html.twig
                    match:
                        Identifier\ContentType: "folder"

ezpage:
    layouts:
        Forsiden:
            name: Forside layout
            template: "tfkfarteBundle:zone:forsidelayout.html.twig"

    enabledLayouts:
        - Forsiden
